name: C-U Around
favicon: null
layout_spectrum: 0.18753
typography_spectrum: 0.46979581261985004
title: C-U Around
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6095021110959351
  lightness: 0.4709490316454321
  saturation: 0.7893356527201831
  rhythmicContrast: 0.4103787327185273
purpose: []
